In [6]:
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, accuracy_score

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [7]:
# データ読み込み（raw）
train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

X = train.drop(['id', 'diagnosed_diabetes'], axis=1)
y = train['diagnosed_diabetes']

print('Train:', train.shape)
print('X:', X.shape, 'y:', y.shape)
print('Target mean:', float(y.mean()))

Train: (700000, 26)
X: (700000, 24) y: (700000,)
Target mean: 0.6232957142857143

In [8]:
# CV前提でシンプル比較（これまでの流れに合わせる）
cat_cols = X.select_dtypes(include=['object']).columns.tolist()
num_cols = [c for c in X.columns if c not in cat_cols]

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print('Categorical cols:', cat_cols)
print('Numeric cols:', len(num_cols))
print('CV:', cv)

Categorical cols: ['gender', 'ethnicity', 'education_level', 'income_level', 'smoking_status', 'employment_status']
Numeric cols: 18
CV: StratifiedKFold(n_splits=5, random_state=42, shuffle=True)

In [9]:
def cv_eval_model(name, model, X, y, cv):
    scoring = {
        'auc': 'roc_auc',
        'acc': 'accuracy',
    }
    scores = cross_validate(
        model,
        X,
        y,
        cv=cv,
        scoring=scoring,
        n_jobs=-1,
        return_train_score=False,
    )
    return {
        'model': name,
        'auc_mean': float(np.mean(scores['test_auc'])),
        'auc_std': float(np.std(scores['test_auc'])),
        'acc_mean': float(np.mean(scores['test_acc'])),
        'acc_std': float(np.std(scores['test_acc'])),
    }

In [10]:
# XGBoost / LightGBM 用：最小限のOrdinal Encoding（raw特徴を壊さないため）
preprocess = ColumnTransformer(
    transformers=[
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_cols),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False,
 )

# これまでの流れに合わせて「最小限」：主にrandom_stateだけ固定（比較の再現性）
xgb = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', XGBClassifier(
        random_state=42,
        n_estimators=281,
        max_depth=6,
        learning_rate=0.05,
        eval_metric='logloss',
    )),
 ])

lgbm = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', LGBMClassifier(
        random_state=42,
    )),
 ])

results = []
results.append(cv_eval_model('xgboost', xgb, X, y, cv))
results.append(cv_eval_model('lightgbm', lgbm, X, y, cv))

pd.DataFrame(results).sort_values('auc_mean', ascending=False)

      model  auc_mean   auc_std  acc_mean   acc_std
1  lightgbm  0.722038  0.000867   0.68070  0.000976
0   xgboost  0.721864  0.000898   0.68093  0.001039

In [11]:
# CatBoost（カテゴリ列をrawで扱える）

from catboost import CatBoostClassifier

def cv_eval_catboost(X, y, cat_cols, cv):
    cat_idx = [X.columns.get_loc(c) for c in cat_cols]
    aucs = []
    accs = []
    for tr_idx, va_idx in cv.split(X, y):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]

        model = CatBoostClassifier(
            iterations=300,
            depth=5,
            learning_rate=0.1,
            loss_function='Logloss',
            eval_metric='AUC',
            random_seed=42,
            verbose=False,
        )
        model.fit(X_tr, y_tr, cat_features=cat_idx)
        proba = model.predict_proba(X_va)[:, 1]
        pred = (proba >= 0.5).astype(int)
        aucs.append(roc_auc_score(y_va, proba))
        accs.append(accuracy_score(y_va, pred))

    return {
        'model': 'catboost',
        'auc_mean': float(np.mean(aucs)),
        'auc_std': float(np.std(aucs)),
        'acc_mean': float(np.mean(accs)),
        'acc_std': float(np.std(accs)),
    }

#results.append(cv_eval_catboost(X, y, cat_cols, cv))
pd.DataFrame(results).sort_values('auc_mean', ascending=False)

      model  auc_mean   auc_std  acc_mean   acc_std
1  lightgbm  0.722038  0.000867   0.68070  0.000976
0   xgboost  0.721864  0.000898   0.68093  0.001039

## 次（アンサンブル）

このノートで上位モデルが決まったら、
- 予測確率の単純平均（soft-vote）
- 重み付き平均
をまず1セルで試します。

## OOF予測の相関確認

モデルの予測の多様性を確認するため、OOF（Out-of-Fold）予測を作成して相関を見る。
- 相関が高い（0.95以上）→ アンサンブル効果薄い
- 相関が低い（0.85未満）→ アンサンブル効果期待大

In [12]:
# OOF予測を作成（LightGBM）
def get_oof_predictions_lgbm(X, y, cv, cat_cols):
    oof_preds = np.zeros(len(X))
    
    preprocess = ColumnTransformer(
        transformers=[
            ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_cols),
        ],
        remainder='passthrough',
        verbose_feature_names_out=False,
    )
    
    for fold, (tr_idx, va_idx) in enumerate(cv.split(X, y)):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
        
        # 前処理
        X_tr_transformed = preprocess.fit_transform(X_tr)
        X_va_transformed = preprocess.transform(X_va)
        
        model = LGBMClassifier(random_state=42, verbose=-1)
        model.fit(X_tr_transformed, y_tr)
        oof_preds[va_idx] = model.predict_proba(X_va_transformed)[:, 1]
        
    return oof_preds

oof_lgbm = get_oof_predictions_lgbm(X, y, cv, cat_cols)
print(f'LGBM OOF AUC: {roc_auc_score(y, oof_lgbm):.5f}')

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

LGBM OOF AUC: 0.72203

In [13]:
# OOF予測を作成（XGBoost）
def get_oof_predictions_xgb(X, y, cv, cat_cols):
    oof_preds = np.zeros(len(X))
    
    preprocess = ColumnTransformer(
        transformers=[
            ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_cols),
        ],
        remainder='passthrough',
        verbose_feature_names_out=False,
    )
    
    for fold, (tr_idx, va_idx) in enumerate(cv.split(X, y)):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
        
        # 前処理
        X_tr_transformed = preprocess.fit_transform(X_tr)
        X_va_transformed = preprocess.transform(X_va)
        
        model = XGBClassifier(
            random_state=42,
            n_estimators=281,
            max_depth=6,
            learning_rate=0.05,
            eval_metric='logloss',
            verbosity=0,
        )
        model.fit(X_tr_transformed, y_tr)
        oof_preds[va_idx] = model.predict_proba(X_va_transformed)[:, 1]
        
    return oof_preds

oof_xgb = get_oof_predictions_xgb(X, y, cv, cat_cols)
print(f'XGB OOF AUC: {roc_auc_score(y, oof_xgb):.5f}')

XGB OOF AUC: 0.72186

In [14]:
# OOF予測を作成（CatBoost）
def get_oof_predictions_catboost(X, y, cv, cat_cols):
    oof_preds = np.zeros(len(X))
    cat_idx = [X.columns.get_loc(c) for c in cat_cols]
    
    for fold, (tr_idx, va_idx) in enumerate(cv.split(X, y)):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
        
        model = CatBoostClassifier(
            iterations=300,
            depth=5,
            learning_rate=0.1,
            loss_function='Logloss',
            eval_metric='AUC',
            random_seed=42,
            verbose=False,
        )
        model.fit(X_tr, y_tr, cat_features=cat_idx)
        oof_preds[va_idx] = model.predict_proba(X_va)[:, 1]
        
    return oof_preds

oof_catboost = get_oof_predictions_catboost(X, y, cv, cat_cols)
print(f'CatBoost OOF AUC: {roc_auc_score(y, oof_catboost):.5f}')

CatBoost OOF AUC: 0.72092

In [17]:
# OOF予測の相関行列を確認
import matplotlib.pyplot as plt
import seaborn as sns

oof_df = pd.DataFrame({
    'LGBM': oof_lgbm,
    'XGB': oof_xgb,
    'CatBoost': oof_catboost,
})
oof_df

            LGBM       XGB  CatBoost
0       0.510893  0.505649  0.492059
1       0.596496  0.589325  0.591661
2       0.250803  0.244613  0.262400
3       0.543574  0.561105  0.558530
4       0.762958  0.771660  0.713786
...          ...       ...       ...
699995  0.401103  0.375743  0.372396
699996  0.604422  0.599582  0.599784
699997  0.648085  0.640598  0.650489
699998  0.604609  0.621305  0.614833
699999  0.706306  0.711562  0.683615

[700000 rows x 3 columns]

In [ ]:

# 相関行列
corr_matrix = oof_df.corr()
print("OOF予測の相関行列:")
print(corr_matrix)
print()

# ヒートマップで可視化
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, fmt='.4f', cmap='coolwarm', center=0.9, 
            vmin=0.85, vmax=1.0, square=True, cbar_kws={'label': 'Correlation'})
plt.title('OOF Predictions Correlation Matrix')
plt.tight_layout()
plt.show()

# 平均相関を計算（対角線を除く）
avg_corr = (corr_matrix.values.sum() - 3) / 6  # 3x3行列で対角線3つを除く
print(f'平均相関: {avg_corr:.4f}')
print()
print('判定:')
if avg_corr >= 0.95:
    print('  → 相関が非常に高い（0.95+）: アンサンブル効果は限定的')
elif avg_corr >= 0.90:
    print('  → 相関が高い（0.90-0.95）: 単純ブレンドで若干改善の余地あり')
elif avg_corr >= 0.85:
    print('  → 相関が中程度（0.85-0.90）: ブレンドで改善期待、スタッキングも検討')
else:
    print('  → 相関が低い（0.85未満）: アンサンブル効果大、スタッキング推奨')

In [18]:
# エラー（誤差）の相関も確認
# 各モデルがどの部分で間違えるかが異なれば、アンサンブルで補完し合える

errors_df = pd.DataFrame({
    'LGBM_error': np.abs(y - oof_lgbm),
    'XGB_error': np.abs(y - oof_xgb),
    'CatBoost_error': np.abs(y - oof_catboost),
})
errors_df

        LGBM_error  XGB_error  CatBoost_error
0         0.489107   0.494351        0.507941
1         0.403504   0.410675        0.408339
2         0.250803   0.244613        0.262400
3         0.456426   0.438895        0.441470
4         0.237042   0.228340        0.286214
...            ...        ...             ...
699995    0.401103   0.375743        0.372396
699996    0.395578   0.400418        0.400216
699997    0.351915   0.359402        0.349511
699998    0.395391   0.378695        0.385167
699999    0.293694   0.288438        0.316385

[700000 rows x 3 columns]

In [ ]:

error_corr = errors_df.corr()
print("エラー（誤差）の相関行列:")
print(error_corr)
print()

# ヒートマップで可視化
plt.figure(figsize=(8, 6))
sns.heatmap(error_corr, annot=True, fmt='.4f', cmap='viridis', center=0.7,
            vmin=0.5, vmax=1.0, square=True, cbar_kws={'label': 'Error Correlation'})
plt.title('Model Errors Correlation Matrix\n(低いほどモデルが異なる部分で間違える＝補完性が高い)')
plt.tight_layout()
plt.show()

avg_error_corr = (error_corr.values.sum() - 3) / 6
print(f'エラー平均相関: {avg_error_corr:.4f}')
print('→ エラー相関が低いほど、モデルが異なるサンプルで間違えるため補完効果が高い')

## LightGBM ベイズ最適化（Optuna）

相関がほぼ1だったため、アンサンブルは効果薄い。
→ 単一モデル（LGBM）のパラメータ最適化に注力

In [19]:
import optuna
from optuna.samplers import TPESampler

# Optunaの目的関数
def objective(trial):
    # パラメータ探索空間
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'random_state': 42,
        'verbose': -1,
    }
    
    # 前処理
    preprocess = ColumnTransformer(
        transformers=[
            ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_cols),
        ],
        remainder='passthrough',
        verbose_feature_names_out=False,
    )
    
    # CV で評価
    auc_scores = []
    for tr_idx, va_idx in cv.split(X, y):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
        
        # 前処理
        X_tr_transformed = preprocess.fit_transform(X_tr)
        X_va_transformed = preprocess.transform(X_va)
        
        # モデル学習
        model = LGBMClassifier(**params)
        model.fit(X_tr_transformed, y_tr)
        
        # 予測
        y_pred = model.predict_proba(X_va_transformed)[:, 1]
        auc = roc_auc_score(y_va, y_pred)
        auc_scores.append(auc)
    
    return np.mean(auc_scores)

print('Optunaによるハイパーパラメータ最適化を開始...')

Optunaによるハイパーパラメータ最適化を開始...

In [20]:
# 最適化実行
study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=42),
    study_name='lgbm_optimization'
)

study.optimize(objective, n_trials=100, show_progress_bar=True)

print('\n最適化完了!')
print(f'Best AUC: {study.best_value:.5f}')
print(f'\nBest Parameters:')
for key, value in study.best_params.items():
    print(f'  {key}: {value}')

[I 2025-12-29 14:14:23,582] A new study created in memory with name: lgbm_optimization

  0%|          | 0/100 [00:00<?, ?it/s]

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:14:47,058] Trial 0 finished with value: 0.7263206578015587 and parameters: {'n_estimators': 218, 'max_depth': 12, 'learning_rate': 0.1205712628744377, 'num_leaves': 98, 'min_child_samples': 19, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.002570603566117598}. Best is trial 0 with value: 0.7263206578015587.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:15:09,852] Trial 1 finished with value: 0.7271227444237002 and parameters: {'n_estimators': 369, 'max_depth': 3, 'learning_rate': 0.2708160864249968, 'num_leaves': 129, 'min_child_samples': 25, 'subsample': 0.5909124836035503, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.00052821153945323}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:15:31,792] Trial 2 finished with value: 0.7230078321939291 and parameters: {'n_estimators': 244, 'max_depth': 5, 'learning_rate': 0.08012737503998542, 'num_leaves': 38, 'min_child_samples': 33, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 6.267062696005991e-07}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:16:06,753] Trial 3 finished with value: 0.7142005664298655 and parameters: {'n_estimators': 281, 'max_depth': 8, 'learning_rate': 0.011711509955524094, 'num_leaves': 99, 'min_child_samples': 21, 'subsample': 0.5325257964926398, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 0.18861495878553936}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:16:21,503] Trial 4 finished with value: 0.7151956810879184 and parameters: {'n_estimators': 187, 'max_depth': 3, 'learning_rate': 0.1024932221692416, 'num_leaves': 77, 'min_child_samples': 16, 'subsample': 0.7475884550556351, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 1.527156759251193, 'reg_lambda': 2.133142332373004e-06}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:16:52,409] Trial 5 finished with value: 0.725049937770346 and parameters: {'n_estimators': 348, 'max_depth': 6, 'learning_rate': 0.05864129169696527, 'num_leaves': 91, 'min_child_samples': 22, 'subsample': 0.9847923138822793, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 2.854239907497756, 'reg_lambda': 1.1309571585271483}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:17:28,699] Trial 6 finished with value: 0.7195400441277824 and parameters: {'n_estimators': 319, 'max_depth': 12, 'learning_rate': 0.01351182947645082, 'num_leaves': 45, 'min_child_samples': 9, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:17:49,611] Trial 7 finished with value: 0.7194471915626565 and parameters: {'n_estimators': 210, 'max_depth': 5, 'learning_rate': 0.06333268775321843, 'num_leaves': 38, 'min_child_samples': 82, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 6.143857495033091e-07}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:18:04,453] Trial 8 finished with value: 0.7228054059290805 and parameters: {'n_estimators': 52, 'max_depth': 11, 'learning_rate': 0.11069143219393454, 'num_leaves': 115, 'min_child_samples': 79, 'subsample': 0.5370223258670452, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 0.5860448217200517}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:18:43,495] Trial 9 finished with value: 0.712714318417364 and parameters: {'n_estimators': 331, 'max_depth': 6, 'learning_rate': 0.012413189635294229, 'num_leaves': 60, 'min_child_samples': 36, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0001778010520878397}. Best is trial 1 with value: 0.7271227444237002.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:19:14,254] Trial 10 finished with value: 0.7279148867622107 and parameters: {'n_estimators': 486, 'max_depth': 3, 'learning_rate': 0.2704729722717776, 'num_leaves': 144, 'min_child_samples': 59, 'subsample': 0.8451235367845726, 'colsample_bytree': 0.6277217293825994, 'reg_alpha': 4.32747580263185e-05, 'reg_lambda': 0.00020590009861590298}. Best is trial 10 with value: 0.7279148867622107.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:19:46,305] Trial 11 finished with value: 0.7278290754915755 and parameters: {'n_estimators': 499, 'max_depth': 3, 'learning_rate': 0.24950292438859467, 'num_leaves': 147, 'min_child_samples': 58, 'subsample': 0.8513496163789993, 'colsample_bytree': 0.5999698896116651, 'reg_alpha': 0.00014870538574514983, 'reg_lambda': 0.00022426976906144702}. Best is trial 10 with value: 0.7279148867622107.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:20:14,660] Trial 12 finished with value: 0.7279492990721834 and parameters: {'n_estimators': 486, 'max_depth': 3, 'learning_rate': 0.2829806896866545, 'num_leaves': 150, 'min_child_samples': 59, 'subsample': 0.8588729908849949, 'colsample_bytree': 0.6106715492431963, 'reg_alpha': 0.0011315562295853888, 'reg_lambda': 3.5542633930517346e-05}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:21:17,682] Trial 13 finished with value: 0.7270095432652098 and parameters: {'n_estimators': 499, 'max_depth': 9, 'learning_rate': 0.03184347392978102, 'num_leaves': 150, 'min_child_samples': 60, 'subsample': 0.8846915468913171, 'colsample_bytree': 0.6274138366049732, 'reg_alpha': 0.0018383753932832785, 'reg_lambda': 2.351315864829065e-05}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:21:46,131] Trial 14 finished with value: 0.7276085125777773 and parameters: {'n_estimators': 417, 'max_depth': 4, 'learning_rate': 0.1826614526342363, 'num_leaves': 131, 'min_child_samples': 100, 'subsample': 0.9501945220447685, 'colsample_bytree': 0.7793992915216571, 'reg_alpha': 0.0014226543913100226, 'reg_lambda': 0.004940630146038981}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:22:24,722] Trial 15 finished with value: 0.7247513482311431 and parameters: {'n_estimators': 430, 'max_depth': 7, 'learning_rate': 0.1691172265814005, 'num_leaves': 126, 'min_child_samples': 47, 'subsample': 0.7967239373760329, 'colsample_bytree': 0.6547281513461738, 'reg_alpha': 0.0001589213203377661, 'reg_lambda': 2.6504074627299538e-05}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:22:55,948] Trial 16 finished with value: 0.717543100993186 and parameters: {'n_estimators': 443, 'max_depth': 4, 'learning_rate': 0.02867105627856683, 'num_leaves': 112, 'min_child_samples': 71, 'subsample': 0.7884745869448389, 'colsample_bytree': 0.5646492922327916, 'reg_alpha': 7.568957196589479e-06, 'reg_lambda': 1.314053143275926e-08}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:23:14,901] Trial 17 finished with value: 0.723596555555855 and parameters: {'n_estimators': 146, 'max_depth': 9, 'learning_rate': 0.20462252532956834, 'num_leaves': 139, 'min_child_samples': 48, 'subsample': 0.9002718545223033, 'colsample_bytree': 0.7533881284358336, 'reg_alpha': 0.011191177414570461, 'reg_lambda': 0.010993417108982812}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:23:43,086] Trial 18 finished with value: 0.7168930249047994 and parameters: {'n_estimators': 389, 'max_depth': 4, 'learning_rate': 0.036046969689776935, 'num_leaves': 20, 'min_child_samples': 68, 'subsample': 0.8135233208242552, 'colsample_bytree': 0.8264423346529436, 'reg_alpha': 6.479872737032084e-08, 'reg_lambda': 4.181087639543297e-08}. Best is trial 12 with value: 0.7279492990721834.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:24:17,183] Trial 19 finished with value: 0.7280285861229225 and parameters: {'n_estimators': 467, 'max_depth': 5, 'learning_rate': 0.14546797732184336, 'num_leaves': 115, 'min_child_samples': 94, 'subsample': 0.7231610042250181, 'colsample_bytree': 0.5471288688885415, 'reg_alpha': 5.799449092292779e-05, 'reg_lambda': 1.549531910614886e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:24:49,018] Trial 20 finished with value: 0.7280126311498419 and parameters: {'n_estimators': 448, 'max_depth': 5, 'learning_rate': 0.14647085239777158, 'num_leaves': 113, 'min_child_samples': 100, 'subsample': 0.709197827480754, 'colsample_bytree': 0.5552573551864604, 'reg_alpha': 4.907564357352296e-07, 'reg_lambda': 8.802075014264656}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:25:18,722] Trial 21 finished with value: 0.7278081790192241 and parameters: {'n_estimators': 441, 'max_depth': 5, 'learning_rate': 0.14421739826337168, 'num_leaves': 116, 'min_child_samples': 99, 'subsample': 0.7252869520994263, 'colsample_bytree': 0.5024708472913341, 'reg_alpha': 1.4329321655479917e-08, 'reg_lambda': 1.0959182167953825e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:25:55,967] Trial 22 finished with value: 0.7238991978748359 and parameters: {'n_estimators': 464, 'max_depth': 6, 'learning_rate': 0.2996691384549942, 'num_leaves': 109, 'min_child_samples': 88, 'subsample': 0.6780059924380187, 'colsample_bytree': 0.5601175209504308, 'reg_alpha': 1.7866498574086175e-07, 'reg_lambda': 5.412753432732342}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:26:27,643] Trial 23 finished with value: 0.7249451415489221 and parameters: {'n_estimators': 409, 'max_depth': 4, 'learning_rate': 0.08640806110705025, 'num_leaves': 77, 'min_child_samples': 89, 'subsample': 0.6273990963830144, 'colsample_bytree': 0.5683427585859017, 'reg_alpha': 6.337886220138659e-07, 'reg_lambda': 0.022849116912737163}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:27:09,334] Trial 24 finished with value: 0.7261696409805991 and parameters: {'n_estimators': 462, 'max_depth': 7, 'learning_rate': 0.14799317340282225, 'num_leaves': 132, 'min_child_samples': 93, 'subsample': 0.7206359238589146, 'colsample_bytree': 0.5427136029881809, 'reg_alpha': 2.90143790815956e-05, 'reg_lambda': 1.4806380078205103e-07}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:27:39,319] Trial 25 finished with value: 0.7273454477184935 and parameters: {'n_estimators': 380, 'max_depth': 5, 'learning_rate': 0.20495954927044188, 'num_leaves': 122, 'min_child_samples': 77, 'subsample': 0.9209379260706607, 'colsample_bytree': 0.6136568762910408, 'reg_alpha': 0.0024809418979064293, 'reg_lambda': 8.605785460357808e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:28:11,800] Trial 26 finished with value: 0.7228426375469075 and parameters: {'n_estimators': 298, 'max_depth': 6, 'learning_rate': 0.04043535628780772, 'num_leaves': 104, 'min_child_samples': 93, 'subsample': 0.7700472005795816, 'colsample_bytree': 0.6687707333900237, 'reg_alpha': 8.621403629592082e-07, 'reg_lambda': 0.0013658322357601917}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:28:45,239] Trial 27 finished with value: 0.7271814994411668 and parameters: {'n_estimators': 452, 'max_depth': 4, 'learning_rate': 0.13665769400072672, 'num_leaves': 85, 'min_child_samples': 69, 'subsample': 0.7145560755150866, 'colsample_bytree': 0.5881270029227951, 'reg_alpha': 2.8939899869851762e-05, 'reg_lambda': 4.505576375884876e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:29:26,688] Trial 28 finished with value: 0.7273593771530439 and parameters: {'n_estimators': 415, 'max_depth': 7, 'learning_rate': 0.08444875071823318, 'num_leaves': 138, 'min_child_samples': 84, 'subsample': 0.6323585999023397, 'colsample_bytree': 0.6456974629573351, 'reg_alpha': 0.009293732218219334, 'reg_lambda': 0.04208921145211446}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:30:20,806] Trial 29 finished with value: 0.7249839765534289 and parameters: {'n_estimators': 470, 'max_depth': 8, 'learning_rate': 0.01893124600345292, 'num_leaves': 95, 'min_child_samples': 74, 'subsample': 0.823736536258928, 'colsample_bytree': 0.5265367292249026, 'reg_alpha': 0.0007332566603302961, 'reg_lambda': 9.518058531245421}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:30:51,169] Trial 30 finished with value: 0.7224598650522882 and parameters: {'n_estimators': 358, 'max_depth': 11, 'learning_rate': 0.22120456500561758, 'num_leaves': 71, 'min_child_samples': 42, 'subsample': 0.7567996839483412, 'colsample_bytree': 0.5019870199268791, 'reg_alpha': 0.03622671632242811, 'reg_lambda': 2.8344474154802356e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:31:23,003] Trial 31 finished with value: 0.7279019466532962 and parameters: {'n_estimators': 497, 'max_depth': 3, 'learning_rate': 0.2895959795900934, 'num_leaves': 141, 'min_child_samples': 61, 'subsample': 0.8338997111968103, 'colsample_bytree': 0.626992212559559, 'reg_alpha': 2.0853816122302644e-05, 'reg_lambda': 6.026826196889256e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:31:54,969] Trial 32 finished with value: 0.7274782520964932 and parameters: {'n_estimators': 482, 'max_depth': 3, 'learning_rate': 0.23796790723092823, 'num_leaves': 120, 'min_child_samples': 54, 'subsample': 0.9235515205369245, 'colsample_bytree': 0.7175361939901794, 'reg_alpha': 0.00027854366358411487, 'reg_lambda': 0.0005617658106321558}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:32:26,728] Trial 33 finished with value: 0.7273847585194556 and parameters: {'n_estimators': 394, 'max_depth': 5, 'learning_rate': 0.16525981973835505, 'num_leaves': 144, 'min_child_samples': 36, 'subsample': 0.645307470751411, 'colsample_bytree': 0.5838253729573973, 'reg_alpha': 7.177816225388954e-05, 'reg_lambda': 0.001538677574706884}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:32:58,225] Trial 34 finished with value: 0.7247940913639794 and parameters: {'n_estimators': 471, 'max_depth': 3, 'learning_rate': 0.12132820083150249, 'num_leaves': 132, 'min_child_samples': 64, 'subsample': 0.6986833568144706, 'colsample_bytree': 0.539283410123455, 'reg_alpha': 2.1713275868605213e-06, 'reg_lambda': 7.993072712002558e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:33:28,602] Trial 35 finished with value: 0.7277602765716589 and parameters: {'n_estimators': 432, 'max_depth': 4, 'learning_rate': 0.25215122689258834, 'num_leaves': 106, 'min_child_samples': 94, 'subsample': 0.6007393082540112, 'colsample_bytree': 0.608777048058718, 'reg_alpha': 9.525110305034481e-06, 'reg_lambda': 2.95565849151222e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:33:59,621] Trial 36 finished with value: 0.726706558784018 and parameters: {'n_estimators': 481, 'max_depth': 3, 'learning_rate': 0.18512554937571693, 'num_leaves': 136, 'min_child_samples': 28, 'subsample': 0.7441565003615873, 'colsample_bytree': 0.7063075403651259, 'reg_alpha': 0.0052452053003223375, 'reg_lambda': 4.973640349460824e-07}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:34:30,138] Trial 37 finished with value: 0.7263067909990146 and parameters: {'n_estimators': 364, 'max_depth': 5, 'learning_rate': 0.09543019311165858, 'num_leaves': 150, 'min_child_samples': 55, 'subsample': 0.9946139426715335, 'colsample_bytree': 0.5517079701563722, 'reg_alpha': 0.0004711962405184201, 'reg_lambda': 0.000357883526209883}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:34:52,400] Trial 38 finished with value: 0.7244921622115152 and parameters: {'n_estimators': 255, 'max_depth': 4, 'learning_rate': 0.12855040860691375, 'num_leaves': 126, 'min_child_samples': 85, 'subsample': 0.7868781620894754, 'colsample_bytree': 0.6385526276838166, 'reg_alpha': 8.859474445317826e-05, 'reg_lambda': 0.07400232485916594}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:35:09,079] Trial 39 finished with value: 0.719283254334853 and parameters: {'n_estimators': 107, 'max_depth': 6, 'learning_rate': 0.06885270146056587, 'num_leaves': 93, 'min_child_samples': 14, 'subsample': 0.8522535962843075, 'colsample_bytree': 0.5885914836799307, 'reg_alpha': 4.6519173348305885e-07, 'reg_lambda': 8.457634663543264e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:35:33,454] Trial 40 finished with value: 0.7133409673816856 and parameters: {'n_estimators': 323, 'max_depth': 3, 'learning_rate': 0.05198302781935727, 'num_leaves': 99, 'min_child_samples': 45, 'subsample': 0.9589407706556485, 'colsample_bytree': 0.6837244449781538, 'reg_alpha': 2.711577419204409e-06, 'reg_lambda': 0.0006758427949483461}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:36:04,806] Trial 41 finished with value: 0.7279639035330406 and parameters: {'n_estimators': 497, 'max_depth': 3, 'learning_rate': 0.2736267683397394, 'num_leaves': 141, 'min_child_samples': 62, 'subsample': 0.8209723118965373, 'colsample_bytree': 0.6232270399568214, 'reg_alpha': 1.940208841301031e-05, 'reg_lambda': 6.982562203624138e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:36:34,410] Trial 42 finished with value: 0.727904410443615 and parameters: {'n_estimators': 447, 'max_depth': 3, 'learning_rate': 0.29938957847337166, 'num_leaves': 144, 'min_child_samples': 65, 'subsample': 0.8782285136480319, 'colsample_bytree': 0.5768204078114684, 'reg_alpha': 6.013373514152436e-05, 'reg_lambda': 0.00017765495415561258}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:37:10,390] Trial 43 finished with value: 0.7270813390546131 and parameters: {'n_estimators': 483, 'max_depth': 5, 'learning_rate': 0.23070983186367183, 'num_leaves': 120, 'min_child_samples': 52, 'subsample': 0.8353774926856037, 'colsample_bytree': 0.5302363816686154, 'reg_alpha': 1.2584274685319034e-05, 'reg_lambda': 9.337734567848246e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:37:40,010] Trial 44 finished with value: 0.7275784514581084 and parameters: {'n_estimators': 408, 'max_depth': 4, 'learning_rate': 0.20316468045828423, 'num_leaves': 134, 'min_child_samples': 78, 'subsample': 0.8062404592605635, 'colsample_bytree': 0.9301194397249982, 'reg_alpha': 0.0002900813074581903, 'reg_lambda': 1.4764838468006119e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:38:11,866] Trial 45 finished with value: 0.7277117295268694 and parameters: {'n_estimators': 500, 'max_depth': 3, 'learning_rate': 0.2518952230762984, 'num_leaves': 143, 'min_child_samples': 97, 'subsample': 0.7436008489693895, 'colsample_bytree': 0.6634458839941628, 'reg_alpha': 4.117291074265005e-06, 'reg_lambda': 0.003232879825030805}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:38:44,743] Trial 46 finished with value: 0.7276276826785679 and parameters: {'n_estimators': 461, 'max_depth': 4, 'learning_rate': 0.15953162771066043, 'num_leaves': 126, 'min_child_samples': 40, 'subsample': 0.7765632269749168, 'colsample_bytree': 0.6092629115872457, 'reg_alpha': 2.3941607440881983e-08, 'reg_lambda': 3.6914960357453037e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:39:32,508] Trial 47 finished with value: 0.7254015616232421 and parameters: {'n_estimators': 431, 'max_depth': 9, 'learning_rate': 0.10704988939250436, 'num_leaves': 150, 'min_child_samples': 51, 'subsample': 0.6933182604317791, 'colsample_bytree': 0.6274659429465103, 'reg_alpha': 0.3335241926254416, 'reg_lambda': 1.3984950101635823e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:40:03,153] Trial 48 finished with value: 0.726850185886921 and parameters: {'n_estimators': 484, 'max_depth': 3, 'learning_rate': 0.18811200654644641, 'num_leaves': 102, 'min_child_samples': 73, 'subsample': 0.8645307567419932, 'colsample_bytree': 0.7471301651360166, 'reg_alpha': 2.4614199308618484e-07, 'reg_lambda': 3.135227952806453e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:40:29,473] Trial 49 finished with value: 0.7275672628810886 and parameters: {'n_estimators': 345, 'max_depth': 4, 'learning_rate': 0.25897308841728506, 'num_leaves': 115, 'min_child_samples': 58, 'subsample': 0.9023167505003055, 'colsample_bytree': 0.5487169382879319, 'reg_alpha': 1.2983027424242666e-06, 'reg_lambda': 0.00894037575737614}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:40:51,447] Trial 50 finished with value: 0.7248351120500066 and parameters: {'n_estimators': 225, 'max_depth': 5, 'learning_rate': 0.11757943190050761, 'num_leaves': 86, 'min_child_samples': 66, 'subsample': 0.5571047430979034, 'colsample_bytree': 0.6946964785901855, 'reg_alpha': 0.0007663419830987632, 'reg_lambda': 2.108817553263919}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:41:21,842] Trial 51 finished with value: 0.7277868283379637 and parameters: {'n_estimators': 449, 'max_depth': 3, 'learning_rate': 0.2993853225790367, 'num_leaves': 144, 'min_child_samples': 63, 'subsample': 0.8813743997121364, 'colsample_bytree': 0.5745577292249734, 'reg_alpha': 4.710152566131366e-05, 'reg_lambda': 0.00019947344154096848}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:41:50,814] Trial 52 finished with value: 0.7277125296887637 and parameters: {'n_estimators': 444, 'max_depth': 3, 'learning_rate': 0.2729407499950938, 'num_leaves': 137, 'min_child_samples': 56, 'subsample': 0.8786513843165298, 'colsample_bytree': 0.5187121279374441, 'reg_alpha': 0.00013491193796356685, 'reg_lambda': 8.23994575519951e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:42:19,642] Trial 53 finished with value: 0.727080833422509 and parameters: {'n_estimators': 426, 'max_depth': 3, 'learning_rate': 0.22258675658387894, 'num_leaves': 144, 'min_child_samples': 67, 'subsample': 0.8545003016376691, 'colsample_bytree': 0.5979661939117602, 'reg_alpha': 5.827540361371628e-05, 'reg_lambda': 0.00020534125756993952}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:42:52,962] Trial 54 finished with value: 0.7276864920196485 and parameters: {'n_estimators': 457, 'max_depth': 4, 'learning_rate': 0.17108520669930968, 'num_leaves': 128, 'min_child_samples': 89, 'subsample': 0.8115607057575485, 'colsample_bytree': 0.5671020075179993, 'reg_alpha': 1.4008652220235233e-05, 'reg_lambda': 0.0007583864949056177}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:43:28,145] Trial 55 finished with value: 0.7258889837754886 and parameters: {'n_estimators': 398, 'max_depth': 6, 'learning_rate': 0.2141729286029552, 'num_leaves': 139, 'min_child_samples': 60, 'subsample': 0.9557964506523474, 'colsample_bytree': 0.6373462546508971, 'reg_alpha': 5.806922694251343e-06, 'reg_lambda': 1.8796741144996185e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:44:18,447] Trial 56 finished with value: 0.7122875893156493 and parameters: {'n_estimators': 479, 'max_depth': 8, 'learning_rate': 0.2808362984571182, 'num_leaves': 148, 'min_child_samples': 49, 'subsample': 0.667447246259345, 'colsample_bytree': 0.8324365266728688, 'reg_alpha': 0.0032165302003088246, 'reg_lambda': 0.00012248451465546344}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:44:51,926] Trial 57 finished with value: 0.7216306156847397 and parameters: {'n_estimators': 498, 'max_depth': 3, 'learning_rate': 0.07326718097703683, 'num_leaves': 131, 'min_child_samples': 82, 'subsample': 0.5070587568226921, 'colsample_bytree': 0.6569950661408603, 'reg_alpha': 0.0011988132187357693, 'reg_lambda': 7.349801975172884e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:45:23,743] Trial 58 finished with value: 0.7273365196353792 and parameters: {'n_estimators': 374, 'max_depth': 5, 'learning_rate': 0.1893779602110247, 'num_leaves': 59, 'min_child_samples': 97, 'subsample': 0.8980913769484997, 'colsample_bytree': 0.620002427430664, 'reg_alpha': 0.00017340340341685163, 'reg_lambda': 1.2164648416203773e-06}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:45:43,153] Trial 59 finished with value: 0.723640103990897 and parameters: {'n_estimators': 185, 'max_depth': 4, 'learning_rate': 0.14630401582927136, 'num_leaves': 109, 'min_child_samples': 72, 'subsample': 0.9274036545356416, 'colsample_bytree': 0.5744270850775403, 'reg_alpha': 3.682897355410687e-05, 'reg_lambda': 3.694833360956578e-05}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:46:13,896] Trial 60 finished with value: 0.7165313454887461 and parameters: {'n_estimators': 437, 'max_depth': 3, 'learning_rate': 0.050098495627227006, 'num_leaves': 121, 'min_child_samples': 100, 'subsample': 0.8396868583531243, 'colsample_bytree': 0.5954574073254911, 'reg_alpha': 0.01996820479274275, 'reg_lambda': 0.0019638074716770136}. Best is trial 19 with value: 0.7280285861229225.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:46:46,172] Trial 61 finished with value: 0.7281471793658738 and parameters: {'n_estimators': 495, 'max_depth': 3, 'learning_rate': 0.2996267028056223, 'num_leaves': 143, 'min_child_samples': 61, 'subsample': 0.8375337667536512, 'colsample_bytree': 0.5556827716601073, 'reg_alpha': 2.3798217704721975e-05, 'reg_lambda': 5.3251195017207314e-05}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:47:16,765] Trial 62 finished with value: 0.727879064075531 and parameters: {'n_estimators': 459, 'max_depth': 3, 'learning_rate': 0.29978995195990155, 'num_leaves': 147, 'min_child_samples': 58, 'subsample': 0.7644293079858282, 'colsample_bytree': 0.5543743847751058, 'reg_alpha': 0.0003543094027465503, 'reg_lambda': 0.0003045879721893073}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:47:48,712] Trial 63 finished with value: 0.7277967027303724 and parameters: {'n_estimators': 471, 'max_depth': 4, 'learning_rate': 0.2485078116585518, 'num_leaves': 141, 'min_child_samples': 63, 'subsample': 0.7940999557162844, 'colsample_bytree': 0.5206081661685419, 'reg_alpha': 8.151494730156505e-05, 'reg_lambda': 5.381835293416566e-06}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:48:32,195] Trial 64 finished with value: 0.7199847023897332 and parameters: {'n_estimators': 486, 'max_depth': 7, 'learning_rate': 0.2686296991044724, 'num_leaves': 137, 'min_child_samples': 67, 'subsample': 0.728889676317314, 'colsample_bytree': 0.5345073344753615, 'reg_alpha': 2.2715538633780358e-05, 'reg_lambda': 1.6930328842102354e-05}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:49:01,518] Trial 65 finished with value: 0.7280382486322464 and parameters: {'n_estimators': 421, 'max_depth': 4, 'learning_rate': 0.223943676297369, 'num_leaves': 145, 'min_child_samples': 75, 'subsample': 0.8226163085406311, 'colsample_bytree': 0.5093364039110949, 'reg_alpha': 1.4542307462964517e-06, 'reg_lambda': 0.0001549875165727539}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:49:30,563] Trial 66 finished with value: 0.7278127196860484 and parameters: {'n_estimators': 422, 'max_depth': 4, 'learning_rate': 0.20487613099196977, 'num_leaves': 133, 'min_child_samples': 75, 'subsample': 0.8223639206025245, 'colsample_bytree': 0.5031665751509499, 'reg_alpha': 8.895357265169785e-08, 'reg_lambda': 5.287617128300825e-05}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:50:01,767] Trial 67 finished with value: 0.7280695890141349 and parameters: {'n_estimators': 470, 'max_depth': 4, 'learning_rate': 0.2282491389867913, 'num_leaves': 146, 'min_child_samples': 87, 'subsample': 0.779500144378388, 'colsample_bytree': 0.5126886170988745, 'reg_alpha': 1.360826260199765e-06, 'reg_lambda': 3.345323373193089e-05}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:50:40,180] Trial 68 finished with value: 0.7198212913885111 and parameters: {'n_estimators': 470, 'max_depth': 5, 'learning_rate': 0.0222495897442955, 'num_leaves': 124, 'min_child_samples': 90, 'subsample': 0.7786070420584889, 'colsample_bytree': 0.504430652614899, 'reg_alpha': 1.1067964962738141e-06, 'reg_lambda': 2.4982380010325794e-05}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:51:10,541] Trial 69 finished with value: 0.727819558379385 and parameters: {'n_estimators': 407, 'max_depth': 4, 'learning_rate': 0.23381375084628053, 'num_leaves': 147, 'min_child_samples': 85, 'subsample': 0.7361182904132616, 'colsample_bytree': 0.5420290826826331, 'reg_alpha': 3.026544337271816e-07, 'reg_lambda': 2.7932143228524443e-07}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:51:45,569] Trial 70 finished with value: 0.7273978679717628 and parameters: {'n_estimators': 493, 'max_depth': 6, 'learning_rate': 0.15533497712326486, 'num_leaves': 130, 'min_child_samples': 95, 'subsample': 0.7064955184795153, 'colsample_bytree': 0.5152721394356112, 'reg_alpha': 4.690798144745287e-06, 'reg_lambda': 0.39389753294526314}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:52:20,024] Trial 71 finished with value: 0.7279663098144088 and parameters: {'n_estimators': 474, 'max_depth': 4, 'learning_rate': 0.17428198288594682, 'num_leaves': 140, 'min_child_samples': 70, 'subsample': 0.8055132152333115, 'colsample_bytree': 0.5635291500616565, 'reg_alpha': 1.2090679149070449e-06, 'reg_lambda': 0.0003739019124999915}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:52:52,281] Trial 72 finished with value: 0.727292952213406 and parameters: {'n_estimators': 465, 'max_depth': 4, 'learning_rate': 0.1318549762028252, 'num_leaves': 140, 'min_child_samples': 91, 'subsample': 0.8256732220466303, 'colsample_bytree': 0.559160328704099, 'reg_alpha': 1.5515792590518583e-06, 'reg_lambda': 0.11197942748913836}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:53:33,122] Trial 73 finished with value: 0.7122991175962022 and parameters: {'n_estimators': 451, 'max_depth': 5, 'learning_rate': 0.010452622019099871, 'num_leaves': 136, 'min_child_samples': 70, 'subsample': 0.8030565294029417, 'colsample_bytree': 0.5319006977769528, 'reg_alpha': 3.522441233122061e-08, 'reg_lambda': 1.2685671185286982}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:54:04,717] Trial 74 finished with value: 0.7278964216359154 and parameters: {'n_estimators': 474, 'max_depth': 5, 'learning_rate': 0.1722467767591408, 'num_leaves': 147, 'min_child_samples': 81, 'subsample': 0.8649875854742407, 'colsample_bytree': 0.5490081477050124, 'reg_alpha': 5.493295796352165e-07, 'reg_lambda': 0.00012355598415891085}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:54:32,086] Trial 75 finished with value: 0.7281027822331462 and parameters: {'n_estimators': 489, 'max_depth': 4, 'learning_rate': 0.19439543135494025, 'num_leaves': 150, 'min_child_samples': 79, 'subsample': 0.764175614580187, 'colsample_bytree': 0.5157606714274677, 'reg_alpha': 1.3820984815695676e-07, 'reg_lambda': 0.0003969277128129323}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:54:51,885] Trial 76 finished with value: 0.726994369901754 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.19537497190963468, 'num_leaves': 115, 'min_child_samples': 76, 'subsample': 0.7601274986301697, 'colsample_bytree': 0.5082055734740838, 'reg_alpha': 1.4135732124766533e-07, 'reg_lambda': 0.000723730193354321}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:55:21,803] Trial 77 finished with value: 0.7267998104297761 and parameters: {'n_estimators': 490, 'max_depth': 10, 'learning_rate': 0.17829973661946139, 'num_leaves': 24, 'min_child_samples': 83, 'subsample': 0.7535660744015161, 'colsample_bytree': 0.5226375565052706, 'reg_alpha': 5.144164558299671e-08, 'reg_lambda': 0.00037401233658448463}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:55:50,282] Trial 78 finished with value: 0.7272360268798191 and parameters: {'n_estimators': 444, 'max_depth': 4, 'learning_rate': 0.14109291168187943, 'num_leaves': 141, 'min_child_samples': 79, 'subsample': 0.7820642289947777, 'colsample_bytree': 0.561789556286427, 'reg_alpha': 3.4372810522699125e-07, 'reg_lambda': 0.021952117239722204}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:56:24,277] Trial 79 finished with value: 0.7270784385290778 and parameters: {'n_estimators': 459, 'max_depth': 5, 'learning_rate': 0.22508925015914427, 'num_leaves': 89, 'min_child_samples': 86, 'subsample': 0.6811895648383893, 'colsample_bytree': 0.5381593274803408, 'reg_alpha': 8.341284205683729e-07, 'reg_lambda': 0.00013140074055983855}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:57:01,981] Trial 80 finished with value: 0.7270707914616611 and parameters: {'n_estimators': 437, 'max_depth': 6, 'learning_rate': 0.1546270912596536, 'num_leaves': 77, 'min_child_samples': 87, 'subsample': 0.7113262697665823, 'colsample_bytree': 0.5828257258665434, 'reg_alpha': 2.1589251917075493e-06, 'reg_lambda': 0.0038127909268917755}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:57:32,886] Trial 81 finished with value: 0.7235437314991064 and parameters: {'n_estimators': 476, 'max_depth': 3, 'learning_rate': 0.09534812785398682, 'num_leaves': 146, 'min_child_samples': 70, 'subsample': 0.8181242161418192, 'colsample_bytree': 0.605184806540559, 'reg_alpha': 8.45933063172784, 'reg_lambda': 4.7844835820130024e-05}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:58:05,435] Trial 82 finished with value: 0.7281020177530629 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.23832291417850346, 'num_leaves': 150, 'min_child_samples': 96, 'subsample': 0.7921760877950726, 'colsample_bytree': 0.5166852017765695, 'reg_alpha': 3.3249401449740515e-06, 'reg_lambda': 0.001227259879330677}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:58:36,277] Trial 83 finished with value: 0.7281064873676658 and parameters: {'n_estimators': 499, 'max_depth': 4, 'learning_rate': 0.24475431235918021, 'num_leaves': 150, 'min_child_samples': 92, 'subsample': 0.7948605396085521, 'colsample_bytree': 0.5152189490895956, 'reg_alpha': 3.0518405952008948e-06, 'reg_lambda': 0.0012142329565596906}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:59:06,452] Trial 84 finished with value: 0.7281008509279353 and parameters: {'n_estimators': 490, 'max_depth': 4, 'learning_rate': 0.2411610197719701, 'num_leaves': 150, 'min_child_samples': 92, 'subsample': 0.8001649160335226, 'colsample_bytree': 0.5134581921890592, 'reg_alpha': 8.656516799301204e-06, 'reg_lambda': 0.000991537098462452}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 14:59:39,290] Trial 85 finished with value: 0.7268985736178476 and parameters: {'n_estimators': 490, 'max_depth': 5, 'learning_rate': 0.2432572271510683, 'num_leaves': 149, 'min_child_samples': 92, 'subsample': 0.7911819180080348, 'colsample_bytree': 0.5169219609747964, 'reg_alpha': 3.934222031968835e-06, 'reg_lambda': 0.0011354622138072387}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:00:09,469] Trial 86 finished with value: 0.7276022558673753 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.21373488130484256, 'num_leaves': 145, 'min_child_samples': 95, 'subsample': 0.765700485495982, 'colsample_bytree': 0.500442912453446, 'reg_alpha': 1.081647679923428e-05, 'reg_lambda': 0.009092744659164766}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:00:37,895] Trial 87 finished with value: 0.7281073066695904 and parameters: {'n_estimators': 484, 'max_depth': 4, 'learning_rate': 0.19835375367632851, 'num_leaves': 150, 'min_child_samples': 97, 'subsample': 0.7329065765918868, 'colsample_bytree': 0.5267345468962126, 'reg_alpha': 7.3166482869045935e-06, 'reg_lambda': 0.001299397410553689}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:01:06,040] Trial 88 finished with value: 0.7280761092578478 and parameters: {'n_estimators': 480, 'max_depth': 4, 'learning_rate': 0.19646136242980858, 'num_leaves': 149, 'min_child_samples': 97, 'subsample': 0.7382471710184461, 'colsample_bytree': 0.5269227719990119, 'reg_alpha': 7.205925142515421e-06, 'reg_lambda': 0.0024771457881323455}. Best is trial 61 with value: 0.7281471793658738.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:01:36,787] Trial 89 finished with value: 0.7282169624144019 and parameters: {'n_estimators': 485, 'max_depth': 4, 'learning_rate': 0.19677178349646662, 'num_leaves': 149, 'min_child_samples': 96, 'subsample': 0.7458045326095891, 'colsample_bytree': 0.5291678557165753, 'reg_alpha': 6.822722163799268e-06, 'reg_lambda': 0.0011376026548390583}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:02:06,574] Trial 90 finished with value: 0.7281550310265394 and parameters: {'n_estimators': 486, 'max_depth': 4, 'learning_rate': 0.20053192589852784, 'num_leaves': 149, 'min_child_samples': 96, 'subsample': 0.742967439087755, 'colsample_bytree': 0.5278753683887412, 'reg_alpha': 6.256364967395443e-06, 'reg_lambda': 0.005107604679685839}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:02:35,374] Trial 91 finished with value: 0.7281594919551255 and parameters: {'n_estimators': 488, 'max_depth': 4, 'learning_rate': 0.19521231942242775, 'num_leaves': 149, 'min_child_samples': 97, 'subsample': 0.7380932516493317, 'colsample_bytree': 0.5311774587512798, 'reg_alpha': 8.751562901601556e-06, 'reg_lambda': 0.0023155247615133235}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:03:04,893] Trial 92 finished with value: 0.7281401493987254 and parameters: {'n_estimators': 487, 'max_depth': 4, 'learning_rate': 0.19462294060626661, 'num_leaves': 150, 'min_child_samples': 97, 'subsample': 0.7341917460520102, 'colsample_bytree': 0.5286773791881737, 'reg_alpha': 6.92765454199647e-06, 'reg_lambda': 0.005576692472275091}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:03:14,500] Trial 93 finished with value: 0.7179896154107952 and parameters: {'n_estimators': 50, 'max_depth': 4, 'learning_rate': 0.2579455092667423, 'num_leaves': 150, 'min_child_samples': 97, 'subsample': 0.7285767140944222, 'colsample_bytree': 0.5334210755881779, 'reg_alpha': 3.0050671983999826e-06, 'reg_lambda': 0.006358538145222289}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:03:43,889] Trial 94 finished with value: 0.7281244712972281 and parameters: {'n_estimators': 490, 'max_depth': 4, 'learning_rate': 0.20506938597781238, 'num_leaves': 142, 'min_child_samples': 91, 'subsample': 0.7516144687842604, 'colsample_bytree': 0.5464908771457463, 'reg_alpha': 7.807771852269628e-06, 'reg_lambda': 0.016119763356517876}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:04:15,355] Trial 95 finished with value: 0.7281456178054336 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.1850130785693558, 'num_leaves': 142, 'min_child_samples': 100, 'subsample': 0.6933839397922227, 'colsample_bytree': 0.5465332562309441, 'reg_alpha': 1.776747762364113e-05, 'reg_lambda': 0.027147908039317402}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:04:27,828] Trial 96 finished with value: 0.7182996790945559 and parameters: {'n_estimators': 72, 'max_depth': 4, 'learning_rate': 0.18392525171633684, 'num_leaves': 137, 'min_child_samples': 100, 'subsample': 0.6945616952215228, 'colsample_bytree': 0.5449433043278841, 'reg_alpha': 1.5360909184094495e-05, 'reg_lambda': 0.017200172322059108}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:05:10,235] Trial 97 finished with value: 0.7207403871671862 and parameters: {'n_estimators': 485, 'max_depth': 12, 'learning_rate': 0.1599504911942072, 'num_leaves': 142, 'min_child_samples': 93, 'subsample': 0.7506506872687139, 'colsample_bytree': 0.5303842804511347, 'reg_alpha': 2.9041679038830842e-05, 'reg_lambda': 0.0426217118470353}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:05:37,012] Trial 98 finished with value: 0.7268595998418923 and parameters: {'n_estimators': 455, 'max_depth': 3, 'learning_rate': 0.19648776548390032, 'num_leaves': 134, 'min_child_samples': 99, 'subsample': 0.6656447576652798, 'colsample_bytree': 0.5518038058693191, 'reg_alpha': 7.294651369458311e-06, 'reg_lambda': 0.0056323588786268185}. Best is trial 89 with value: 0.7282169624144019.

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2025-12-29 15:06:09,403] Trial 99 finished with value: 0.7276023205812396 and parameters: {'n_estimators': 490, 'max_depth': 5, 'learning_rate': 0.20897624398163994, 'num_leaves': 142, 'min_child_samples': 89, 'subsample': 0.7212328027834959, 'colsample_bytree': 0.5273774024599236, 'reg_alpha': 1.9120668079290507e-05, 'reg_lambda': 0.012133186781510062}. Best is trial 89 with value: 0.7282169624144019.

最適化完了!
Best AUC: 0.72822

Best Parameters:
  n_estimators: 485
  max_depth: 4
  learning_rate: 0.19677178349646662
  num_leaves: 149
  min_child_samples: 96
  subsample: 0.7458045326095891
  colsample_bytree: 0.5291678557165753
  reg_alpha: 6.822722163799268e-06
  reg_lambda: 0.0011376026548390583

In [21]:
# 最適化の過程を可視化
fig = optuna.visualization.plot_optimization_history(study)
fig.show()

# パラメータの重要度
fig = optuna.visualization.plot_param_importances(study)
fig.show()

In [22]:
# 最適化されたパラメータで最終モデルを訓練してテストデータに予測
best_params = study.best_params.copy()
best_params['random_state'] = 42
best_params['verbose'] = -1

# 前処理
preprocess = ColumnTransformer(
    transformers=[
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_cols),
    ],
    remainder='passthrough',
    verbose_feature_names_out=False,
)

# 全データで学習
X_transformed = preprocess.fit_transform(X)
X_test = test.drop(['id'], axis=1)
X_test_transformed = preprocess.transform(X_test)

final_model = LGBMClassifier(**best_params)
final_model.fit(X_transformed, y)

# テストデータに予測
test_preds = final_model.predict_proba(X_test_transformed)[:, 1]

# サブミッションファイル作成
submission = pd.DataFrame({
    'id': test['id'],
    'diagnosed_diabetes': test_preds
})

submission.to_csv('submission_lgbm_optimized.csv', index=False)
print('✅ submission_lgbm_optimized.csv を保存しました')
print(f'Best CV AUC: {study.best_value:.5f}')

c:\Users\mikku\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning:

X does not have valid feature names, but LGBMClassifier was fitted with feature names

✅ submission_lgbm_optimized.csv を保存しました
Best CV AUC: 0.72822

### 補足: 木の深さを変えたアンサンブルについて

**推奨しない理由:**
- 同じLGBMアルゴリズムで深さだけ変えても、予測の相関は依然として高い（0.95+）
- 計算コストが増えるが、スコア改善は0.001未満の微増程度
- オーバーフィッティングのリスクが増加

**より効果的な代替案:**
1. ✅ **パラメータ最適化**（上記実装済み）- 単一モデルの性能を最大化
2. **特徴量エンジニアリング** - 多項式特徴、交互作用項、集約統計量など
3. **異なるアルゴリズム** - もし多様性が必要なら、NN（TabNet/MLP）やCatBoost強化を検討